#! /bin/sh -eu

# Your source directory. Default is the config dir, if it can be found.
SRC_DIR=

# Executable name, from the executable stanza of your cabal file.
# The script will try to guess it if not specified.
EXE_NAME=xmonad-config

# Cabal path
CABAL=$HOME/.ghcup/bin/cabal

# Config source
SOURCE=$HOME/.xmonad/xmonad.hs

# Cache file for sum check
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/xmonad-checksum"
##############################################################################

# config

output="$1"

if [ "$SRC_DIR" = "" ]; then
    # look for the config directory, fall back to the old one
    SRC_DIR="${XMONAD_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.xmonad}}"
    if test -f "$SRC_DIR/build"; then
	:
    else
	SRC_DIR="$HOME/.xmonad"
    fi
fi
cd "$SRC_DIR"

if [ "$EXE_NAME" = "" ]; then
    # try to extract the name of the executable
    EXE_NAME="$(awk '!done && /^executable / {print $2; done = 1}' *.cabal)"
    # note that there should be only one cabal file or cabal will report a
    # conflict; any utilities should be listed after the xmonad executable
fi

# do it to it

PREV_SUM=""
if [ -f $CACHE ]; then
    PREV_SUM="$(cat $CACHE)"
fi
CURR_SUM="$(md5sum ~/.dotfiles/xmonad/xmonad.hs | cut -d " " -f1)"

if [ "$CURR_SUM" = "$PREV_SUM" ]; then
    echo "Source file up to date"
    exit 0
fi

echo "Writing source file checksum to $CACHE"
md5sum ~/.dotfiles/xmonad/xmonad.hs | cut -d " " -f1 > $CACHE

d="$(dirname "$output")"
f="$(basename "$output")"
first=0
for exe in $EXE_NAME; do
    $CABAL install exe:"$EXE_NAME" \
	  --enable-executable-stripping \
	  --enable-optimization=2 \
	  --installdir="$d" \
	  --overwrite-policy=always
    # NB. a cabal bug may mean it doesn't actually get stripped
    # we assume the first executable in the list is the new xmonad
    if [ $first = 0 ]; then
	first=1
	if [ "$f" = "$exe" ]; then
	    : someone will try it…
	else
	    ln -sf "$exe" "$output"
	fi
    elif [ "$f" = "$exe" ]; then
	# the link above just got replaced with a direct link into the
	# cabal package
	echo I hope you know what you\'re doing... >&2
    fi
done
