#!/bin/bash
toggle=`amixer -D pulse get Master | grep "]$" |awk '{print $6}'| sed -e 's/\[//' -e 's/\]//' | head -n 1`
if [[ $toggle == "on" ]]; then
	icon="墳"
else
	icon="婢"

fi
percent=`amixer -D pulse get Master | grep % |awk '{print $5}'|sed -e 's/\[//' -e 's/\]//' | head -n 1`
echo "$icon  $percent"

